### ISSUE TITLE
TypeError: this.subClient.psubscribe is not a function

### ISSUE THREAD

**Issue by aekryz1993** [socketio/socket.io-redis-adapter#423] opened 2021-10-25 13:59 UTC
`pubClient.duplicate()` return object with a property function named pSubscribe (S is uppercase). and at /node_modules/@socket.io/redis-adapter/dist/index.js the property is named psubscribe (S is lowercase).

For now, The issue is fixed by adding property psubscribe (S is lowercase):
```
const { Server } = require("socket.io");
const { createAdapter } = require("@socket.io/redis-adapter");
const { createClient } = require("redis");

const io = new Server();

const pubClient = createClient({ host: "localhost", port: 6379 });

const subClient = pubClient.duplicate();
subClient.psubscribe = subClient.pSubscribe
```
Versions:
```
"redis": "^4.0.0-rc.1",
"@socket.io/redis-adapter": "^7.0.0",
```
The error was:
```
error: TypeError: this.subClient.psubscribe is not a function
          at new RedisAdapter (/node_modules/@socket.io/redis-adapter/dist/index.js:64:24)
          at new OurOwnRedisAdapter (/lib/websocket-adapter.js:39:5)
          at Namespace._initAdapter (/node_modules/socket.io/dist/namespace.js:40:24)
          at Server.adapter (/node_modules/socket.io/dist/index.js:133:17)
          at module.exports (/lib/websocket.js:27:6)
          at Server.<anonymous> (/server.js:25:16)
          at Object.onceWrapper (events.js:421:28)
          at Server.emit (events.js:315:20)
          at emitListeningNT (net.js:1352:10)
          at processTicksAndRejections (internal/process/task_queues.js:79:21)
```

**Comment by darrachequesne** [comment] 2021-11-14 05:55
An issue was opened here: https://github.com/redis/node-redis/issues/1718

Note: we could also use base64 encoding, but it would be a backward incompatible change

**Comment by NarHakobyan** [comment] 2021-11-29 08:38
Hi guys, as I see node-redis has merged the PR, so do you have plans to release a new version?

**Comment by darrachequesne** [comment] 2021-11-29 11:30
I'm working on this.

**Comment by NarHakobyan** [comment] 2021-11-29 12:14
@darrachequesne thank you 🙏

**Comment by yanush** [comment] 2021-11-29 14:59
I ended up switching to ioredis because of this issue.
It was really quick migration

**Comment by darrachequesne** [comment] 2021-11-30 00:21
Support for `redis@4` was added in release 7.1.0: https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.1.0

**Closed by darrachequesne** 2021-11-30 00:21 UTC
Labels: enhancement

**Comment by djaffer** [comment] 2021-12-02 21:15
Please in the documentation add connect if it is explicitly required or the package doing when the client is passed.

**Comment by yanush** [comment] 2021-12-11 08:42
you added support for node-redis and broke the support for ioredis
"clientSub.PSUBSCRIBE is not a function" at new RedisAdapter (..../node_modules/@socket.io/redis-adapter/dist/index.js:76:24)

**Comment by darrachequesne** [comment] 2021-12-13 08:11
@yanush that's weird, I was not able to reproduce, and it seems there is no `PSUBSCRIBE` (all uppercase) command in the codebase. Could you please check?

**Comment by yanush** [comment] 2021-12-13 09:56
@darrachequesne I think you are right. It might be some patched code I tried to fix the node-redis v4 support.
Thanks!

**Comment by darrachequesne** [comment] 2021-12-14 07:57
@djaffer done!
